# Generated by Django 2.1 on 2018-08-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breuninger_shop', '0002_auto_20180810_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='currency',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='size',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='price',
            field=models.FloatField(),
        ),
    ]
